"""
Signal — a trading decision generated by a strategy.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class SignalType(str, Enum):
    BUY  = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE_LONG  = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"
    SHORT = "SHORT"          # For short-selling enabled accounts


class SignalStrength(str, Enum):
    STRONG = "STRONG"   # High confidence
    NORMAL = "NORMAL"   # Standard
    WEAK   = "WEAK"     # Low confidence — may be filtered by risk gate


@dataclass
class Signal:
    """
    A trading signal produced by a strategy.

    strategy_id: Name/ID of the strategy that generated this signal
    symbol     : Target instrument, e.g. "hk00700"
    signal_type: BUY | SELL | HOLD | CLOSE_LONG | CLOSE_SHORT | SHORT
    strength   : STRONG | NORMAL | WEAK
    price      : Reference price at signal generation
    quantity   : Suggested quantity (shares). 0 = let risk/sizing module decide.
    confidence : 0.0 to 1.0 — used by ML strategies
    metadata   : Arbitrary dict for debug info (e.g. {"rsi": 28.3, "macd": 0.12})
    """

    strategy_id: str
    symbol: str
    signal_type: SignalType
    price: float
    ts: datetime = field(default_factory=datetime.now)
    strength: SignalStrength = SignalStrength.NORMAL
    quantity: int = 0
    confidence: float = 1.0
    metadata: dict = field(default_factory=dict)
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def is_entry(self) -> bool:
        return self.signal_type in (SignalType.BUY, SignalType.SHORT)

    def is_exit(self) -> bool:
        return self.signal_type in (
            SignalType.SELL, SignalType.CLOSE_LONG, SignalType.CLOSE_SHORT
        )

    def __repr__(self) -> str:
        return (
            f"Signal({self.strategy_id} → {self.signal_type.value} "
            f"{self.symbol} qty={self.quantity} @ {self.price:.4f} "
            f"conf={self.confidence:.0%})"
        )
